FROM node:20

RUN curl -fsSL https://get.pnpm.io/install.sh | SHELL="$(which bash)" bash -

ENV PATH="/root/.local/share/pnpm:$PATH"

WORKDIR /usr/src/app

COPY package*.json ./

RUN pnpm install

COPY . .

ARG VITE_API_BASE_URL
ARG VITE_EDITOR_KEY
RUN printf "VITE_API_BASE_URL=%s\nVITE_EDITOR_KEY=%s\n" \
    "$VITE_API_BASE_URL" "$VITE_EDITOR_KEY" > .env

RUN pnpm run build

EXPOSE 8080

CMD ["pnpm", "preview", "--host", "0.0.0.0"]