FROM node:20

RUN curl -fsSL https://get.pnpm.io/install.sh | SHELL="$(which bash)" bash -

ENV PATH="/root/.local/share/pnpm:$PATH"

WORKDIR /usr/src/app

COPY package*.json ./

RUN pnpm install

COPY . .

RUN pnpm run build

EXPOSE 8080

CMD ["pnpm", "preview"]