services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WHITELISTED_DOMAINS=${WHITELISTED_DOMAINS}
      - APP_URL=${APP_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
    depends_on:
      - db
    networks:
      - portofolio_app_network

  frontend:
    build:
      context: ./frontend/vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_EDITOR_KEY=${VITE_EDITOR_KEY}
    networks:
      - portofolio_app_network

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portofolio_app_network

volumes:
  mysql_data:

networks:
  portofolio_app_network:
    driver: bridge
