version: "3"
services:
  backend:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - WHITELISTED_DOMAINS=${WHITELISTED_DOMAINS}
      - APP_URL=${APP_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend/vue
    ports:
      - "80:5173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_EDITOR_KEY=${VITE_EDITOR_KEY}
    volumes:
      - ./frontend/vue:/usr/src/app
      - /usr/src/app/node_modules
