services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    networks:
      - portofolio_app_network

  frontend:
    build:
      context: ./frontend/vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./frontend/vue/.env
    networks:
      - portofolio_app_network

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portofolio_app_network

volumes:
  mysql_data:

networks:
  portofolio_app_network:
    driver: bridge
