FROM node:20

RUN curl -fsSL https://get.pnpm.io/install.sh | SHELL="$(which bash)" bash -

ENV PATH="/root/.local/share/pnpm:$PATH"

WORKDIR /usr/src/app

COPY package*.json ./

RUN pnpm install

RUN pnpm add -g sequelize-cli

COPY . .

EXPOSE 3000

CMD ["pnpm", "start"]