FROM node:20

RUN curl -fsSL https://get.pnpm.io/install.sh | SHELL="$(which bash)" bash -

ENV PATH="/root/.local/share/pnpm:$PATH"

WORKDIR /usr/src/app

COPY api/package*.json ./

RUN pnpm install

COPY api/ ./

EXPOSE 3000

CMD ["pnpm", "start"]